### PR TITLE
Input clean up

### PR DESCRIPTION
**Pull request by etoumey**
Still have some warnings... mostly casting/data-type stuff, see what u think

### CODE REVIEW

**Comment by jtoumey** [comment]
Cool, that looks good, way better than the B.S. i had going on. I will pull it and merge it when I get home.

**Comment by jtoumey** [comment]
Is this what your warnings look like? 
make_newinput

**Comment by jtoumey** [comment]
Ok, most of those were from my old code ;) cleaned 'em up. fixed a warning for file echo. pushed to master. compile and see if it works! It works for me but I have yet to try and break it...

**Comment by etoumey** [comment]
yeah those are the warnings i had lol, ill snag a copy and see

**Pull request merged**
