### PR TITLE
file input and processing

### PR DESCRIPTION
**Pull request by etoumey**
CHeck out the new function. 

Includes updates to main

You will need to change the file path in the new function. Right now it is to "/home/etoumey/" idk where ur stuff is saved.

### CODE REVIEW

**Comment by etoumey** [comment]
i added some stuff to new processing function. I just forgot how to do pull request

**Comment by jtoumey** [comment]
Cool, looks good. A couple things... 
1. We need a way to determine how many elements (time equivalent) should be in the array. Then we can allocate the memory for safety and speed. I am not sure how TF to do this.

xml_time_trk
1. Check out the screenshot of the *_.gpx_ file above. There's a `<time>` tag for the initial time. Then, there are additional `<time>` tags that fall under the `<trk>` tag. Those are the ones we need. We can use some sort of escape condition that is activated after entering the `<trk>` heading. 
2. I have an idea for finding the `<time>` tag without all those conditionals. I'll make a branch and push it later tonight. 
3. I was able to compile and run the new function, no problem. For the `tss.sh` script though, if I change the directory every time I work on it, then we'll keep changing each other's paths every time we commit. Actually, I can just never commit it. Just let me know if you make a change and I'll pull the new version. Can you explain how to use it lol.

**Comment by etoumey** [comment]
1. Yeah i see about the  trk business. I was just trying to get something out that could scan for the tags as a starting point. It does it pretty fast. I mean in computational time, probably an eternity but whatever. 
2.  I tried grabbing a line at a time into an array and looking at <code> strcat(line[1],line[2],line[3]) </code>. That caused a shitton of errors and i wasn't having it. I was working with the <code> getline </code> command
3. okay, so the tss.sh script is just shorthand for me. Like i was typing <code> gcc get_input.c calc_hr_zone.c main.c -o a.out -lm
   ./a.out </code>
   With the bash script, you can type <code> chmod +x tss.sh </code>. That way you can just type <code> ./tss.sh </code> and the series of commands to compile and execute the prog are run. It is really just a quicker way to make everything happen. That script can be more of like a personal thing. Doesn't require much alteration throughout development.

**Comment by jtoumey** [comment]
To your first two notes, cool, perfect. 

For 3., So doesn't the script pass in the file name? OH is it hardcoded??? Is that what we talked about today HAHA. So I can just compile and run, however I want? I don't have to run the script to feed it the input file ?

**Comment by etoumey** [comment]
Yeah so right now it's hard-coded. We could change it or not.

And right, U can use ur makefile business or gcc or wutevs. 

for me, bash script is a good intermediary between the gibberish and specific syntax of C and the more familiar realm of unix commands lol

**Comment by etoumey** [comment]
OH Also, the conditional is "Short-Circuit Logic"

So it only tests <code> if(c == 't') </code>

you know? it doesn't run through 't', 'i', 'm', 'e' for every set of 4.

But hopefully you know a better way

**Pull request merged**
